bq2597x_charger_main-y += bq2597x_charger.o
obj-$(CONFIG_BQ2597X_CHARGE_PUMP)	+= bq2597x_charger_main.o bq2597x_charger_iio.o

mi_qc3_pd_policy-y += pd_policy_manager.o cp_qc30.o
obj-$(CONFIG_MI_QC3_PD_POLICY)	+= mi_qc3_pd_policy.o
